image: rust:1.45

variables:
  REPO: gitlab.com
  GROUP: oraksil
  PROJECT: gipan
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  BUILD_HOME: $CI_PROJECT_DIR/target
  MAME_HOME: $CI_PROJECT_DIR/mame 

stages:
  - test

cache:
  paths:
    - $MAME_HOME
    - $CARGO_HOME
    - $BUILD_HOME

before_script:
  - apt -y update
  - apt install -y cmake clang
  - apt install -y libx264-dev libvpx-dev libopus-dev nanomsg-utils
  - ln -s libnanomsg.so.5 /usr/lib/x86_64-linux-gnu/libnanomsg.so
  
  - if [ ! -f $MAME_HOME/libmame64.so ]; then wget https://oraksil.s3.ap-northeast-2.amazonaws.com/etc/libmame64.so -P $MAME_HOME; fi

unit_tests:
  stage: test
  script:
    - cargo test
