[package]
name = "gipan"
version = "0.1.0"
authors = ["gamz <gamzabaw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "0.3.2"
bytes = "0.5.2"

nanomsg = "0.7.2"
crossbeam-channel = "0.4"

av-data = "0.2"
av-codec = "0.2"
av-format = "0.2"

x264 = { git = "https://github.com/rust-av/x264-rs.git", version = "0.1.0" }
libvpx = { git = "https://github.com/rust-av/vpx-rs", features = ["codec-trait"] }

libemu = { path = "libemu" }
